### ISSUE TITLE
404 Requested Entity Was Not Found?

### ISSUE THREAD

**Issue by AsteaDevelopment** [bytefish/FcmSharp#48] opened 2018-12-07 17:17 UTC
Hello,

I am receiving the following response when using FcmSharp. This was not the case 1-2 months ago, I just started doing some recent testing and this is the case. Is there an easy work around for this? Google search says it is related to expired tokens, but it looks like FcmSharp handles that.

`{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "errors": [
      {
        "message": "Requested entity was not found.",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}
`

**Comment by AsteaDevelopment** [comment] 2018-12-07 17:17
I also verified my service account.json file, it is using the latest possible.

**Comment by bytefish** [comment] 2018-12-07 17:22
Thanks for the Bug Report. I will look into it, but it may take a day or two.

**Comment by AsteaDevelopment** [comment] 2018-12-07 17:32
@bytefish, thanks. I do not understand how it is not registered though. The client I can see a registration id token being generated. I am using the phonegap push plugin, maybe a problem on their end then?

**Comment by bytefish** [comment] 2018-12-07 19:45
@AsteaDevelopment I am not sure. Maybe you double check if you are using the correct token? I think you can also send Push Messages from the Firebase Console Website. Maybe you can try to send a message with it for the problematic token and see what it outputs? It probably gives additional errors.

**Comment by kehollin** [comment] 2018-12-07 20:18
I get a 404 when I delete the app from my phone, so yeah could definitely
be an invalid token.

On Dec 7, 2018 12:46 PM, "Philipp Wagner" <notifications@github.com> wrote:

@AsteaDevelopment <https://github.com/AsteaDevelopment> I am not sure.
Maybe you double check if you are using the correct token? I think you can
also send Push Messages from the Firebase Console Website. Maybe you can
try to send a message with it for the problematic token and see what it
outputs? It probably gives additional errors.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bytefish/FcmSharp/issues/48#issuecomment-445344576>,
or mute
the thread

**Comment by bytefish** [comment] 2018-12-07 20:36
@kehollin Thanks for your feedback!

**Comment by bytefish** [comment] 2018-12-09 08:34
I am closing the issue, because I think the 404 is a valid return code from Firebase and occurs, when the Token is invalid... for example due to uninstalling the app. @AsteaDevelopment Please reopen, if you can reproduce the problem and identify it is a problem in FcmSharp. At the moment I don't think there is a problem on my side.

**Closed by bytefish** 2018-12-09 08:34 UTC
Labels: enhancement, not a bug, question
